Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\coaching_management\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\coaching_management\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed: /coaching_management/teacherapi/
Method Not Allowed: /coaching_management/teacherapi/
Internal Server Error: /coaching_management/teacherapi/
Traceback (most recent call last):
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TeacherModelViewSet.create() missing 1 required positional argument: 'args'
Method Not Allowed: /coaching_management/teacherapi/
Watching for file changes with StatReloader
Internal Server Error: /coaching_management/teacherapi/4
Traceback (most recent call last):
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/coaching_management/teacherapi/4/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Internal Server Error: /coaching_management/teacherapi/4
Traceback (most recent call last):
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PATCH, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PATCH data. Change your form to point to 127.0.0.1:8000/coaching_management/teacherapi/4/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Method Not Allowed: /coaching_management/teacherapi/
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed: /coaching_management/teacherapi/
Internal Server Error: /coaching_management/teacherapi/4
Traceback (most recent call last):
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PATCH, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PATCH data. Change your form to point to 127.0.0.1:8000/coaching_management/teacherapi/4/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\coaching_management\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /teacherapi/1/
Internal Server Error: /coaching_management/teacherapi/
Traceback (most recent call last):
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TeacherModelViewSet.create() missing 1 required positional argument: 'args'
Internal Server Error: /coaching_management/teacherapi/
Traceback (most recent call last):
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TeacherModelViewSet.create() missing 1 required positional argument: 'args'
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /coaching_management/teacherapi/
Method Not Allowed: /coaching_management/teacherapi/
Method Not Allowed: /coaching_management/teacherapi/
Unsupported Media Type: /coaching_management/teacherapi/4/
Unsupported Media Type: /coaching_management/teacherapi/4/
Unsupported Media Type: /coaching_management/teacherapi/4/
Watching for file changes with StatReloader
Not Found: /swagger-editor
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /favicon.ico
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /teacherapi/
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TeacherModelViewSet.create() missing 1 required positional argument: 'args'
Internal Server Error: /teacherapi/17
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PATCH, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PATCH data. Change your form to point to 127.0.0.1:8000/teacherapi/17/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /teacherapi/
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TeacherModelViewSet.create() missing 1 required positional argument: 'args'
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /teacherapi/
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\t_info\views.py", line 54, in create
    return success_response(serializer.data, status=201, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: success_response() got an unexpected keyword argument 'status'
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /teacherapi/
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'dict'>`
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed: /teacherapi/
Method Not Allowed: /teacherapi/
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\utils.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\utils.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\utils.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\utils.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\coaching_management\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\utils.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\utils.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Data listed successfully
Data created successfully
Method Not Allowed: /teacherapi/
Internal Server Error: /teacherapi/18
Traceback (most recent call last):
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PATCH, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PATCH data. Change your form to point to 127.0.0.1:8000/teacherapi/18/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Internal Server Error: /teacherapi/18
Traceback (most recent call last):
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PATCH, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PATCH data. Change your form to point to 127.0.0.1:8000/teacherapi/18/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Method Not Allowed: /teacherapi/
Method Not Allowed: /teacherapi/
Data updated successfully
Data updated successfully
Data deleted successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
Data created successfully
D:\Training\Django\Coaching\coaching_management\coaching_management\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
Data listed successfully
D:\Training\Django\Coaching\coaching_management\coaching_management\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\coaching_management\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Data listed successfully
Data listed successfully
Data listed successfully
Data listed successfully
Data listed successfully
Data listed successfully
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
Data listed successfully
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
Internal Server Error: /teacherapi/
Traceback (most recent call last):
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
Internal Server Error: /teacherapi/
Traceback (most recent call last):
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
An error occurred during listing: When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.
Internal Server Error: /teacherapi/
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
Internal Server Error: /teacherapi/
Traceback (most recent call last):
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
An error occurred during listing: cannot access local variable 'page' where it is not associated with a value
Internal Server Error: /teacherapi/
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
Data listed successfully
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
Internal Server Error: /teacherapi/
Traceback (most recent call last):
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "D:\Training\Django\Coaching\coaching_management\venv\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
Data listed successfully
Data listed successfully
Data listed successfully
Data listed successfully
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
Data listed successfully
Data listed successfully
Data listed successfully
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
Data listed successfully
Data listed successfully
Data listed successfully
D:\Training\Django\Coaching\coaching_management\t_info\views.py changed, reloading.
Watching for file changes with StatReloader
An error occurred during listing: Invalid page.
Data listed successfully
Data listed successfully
Watching for file changes with StatReloader
Data listed successfully
